language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd lib/docker && bash ./build.sh
